org: leadlly
app: leadlly-mentor-api

service: leadlly-mentor-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ap-south-1
  environment:
    FRONTEND_URL: https://mentor.leadlly.in
    JWT_SECRET: ${ssm:/leadlly/JWT_SECRET}
    REDIS_URI: ${ssm:/leadlly/REDIS_URI}
    LEADLLY_DB_URL: ${ssm:/leadlly/LEADLLY_DB_URL}
    LEADLLY_QUESTIONS_DB_URL: ${ssm:/leadlly/LEADLLY_QUESTIONS_DB_URL}
    SMTP_HOST: smtp.gmail.com
    SMTP_PORT: 465
    SMTP_SERVICE: gmail
    SMTP_USER: ${ssm:/leadlly/SMTP_USER}
    SMTP_PASS: ${ssm:/leadlly/SMTP_PASS}

package:
  exclude:
    - .git/**
    - .env
    - src/**

functions:
  api:
    handler: dist/server.handler
    events:
      - httpApi: "*"
